// Auto-generated by contracts/scripts/generate-relayer-config.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

import type { ChainConfig } from "./types.js";

// Chain configurations with deployment addresses
export const CHAIN_CONFIGS: Record<string, ChainConfig> = {
  etherlinkShadownet: {
    chainId: 127823,
    name: "Etherlink Shadownet",
    rpcUrl:
      process.env.ETHERLINK_SHADOWNET_RPC ||
      "https://node.shadownet.etherlink.com",
    policyManagerAddress:
      "0x93344be5b4170ad7430c7096953d048a4a03c58c" as `0x${string}`,
    startBlock: 2716400, // Start slightly before deployment block
    pollIntervalMs: 15000,
    batchSize: 500, // RPC limit is 500 blocks
    confirmations: 1,
    enabled: true,
    minGasFees: {
      maxPriorityFeePerGas: 100000n,
      maxFeePerGas: 1000000n,
    },
  },
  etherlinkTestnet: {
    chainId: 128123,
    name: "Etherlink Testnet",
    rpcUrl:
      process.env.ETHERLINK_TESTNET_RPC ||
      "https://node.ghostnet.etherlink.com",
    policyManagerAddress:
      "0x0000000000000000000000000000000000000000" as `0x${string}`,
    startBlock: 0,
    pollIntervalMs: 15000,
    batchSize: 5000,
    confirmations: 1,
    enabled: false,
    minGasFees: {
      maxPriorityFeePerGas: 100000n,
      maxFeePerGas: 1000000n,
    },
  },
} as const;

// Deployment metadata
export const DEPLOYMENTS = {
  "127823": {
    chainId: 127823,
    chainName: "etherlinkTestnet",
    deployedAt: "2026-02-14T07:38:47Z",
    deployer: "0x9DB2507a09137c9fBE3f9F5404d4858B5C67AF6B",
    deployBlock: 2716481,
    contracts: {
      blinksPolicyManager: "0x93344be5b4170ad7430c7096953d048a4a03c58c",
    },
    addresses: {
      usdc: "0xdff6bf7fbcbba7142e0b091a14404080dca852bb",
      feeRecipient: "0x2446C3FcA8234af53E719D77c387E54C34aD162E",
    },
    txHash:
      "0x152f560df42d94772d21c9133bf39e4d2efb83348cd9af6fde14f4de875bc348",
  },
} as const;

// Get enabled chains
export function getEnabledChainConfigs(): ChainConfig[] {
  return Object.values(CHAIN_CONFIGS).filter((c) => c.enabled);
}

// Get chain config by ID
export function getChainConfigById(chainId: number): ChainConfig | undefined {
  return Object.values(CHAIN_CONFIGS).find((c) => c.chainId === chainId);
}
